# Site settings
# in the templates available like {{ site.myvariable }}.
title: Moog
email: quaizy@snu.ac.kr
brand: Sungmook Leem (Moog)
headline: UX Designer, Engineer (Maybe wannabe until now)
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://Moog303.github.io" # the base hostname & protocol for your site
copyright: 2018 Moog@

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: quaizy@snu.ac.kr
phone: +82-10-2583-4802

# Tracking
googleAnalitycsID: UA-83933844-1

